"""sync sqlalchemy metadata

Revision ID: 4e5b2f3c2a48
Revises: 0001
Create Date: 2026-03-26 23:32:46.730976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e5b2f3c2a48'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_messages', 'message',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('ticket_messages', 'is_internal',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('ticket_messages', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ticket_messages', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ticket_messages_author_id'), 'ticket_messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.add_column('tickets', sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='ticketpriority'), nullable=True, server_default='normal'))
    op.alter_column('tickets', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tickets', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=mysql.ENUM('pending', 'in_process', 'done', 'canceled'),
               nullable=False)
    op.alter_column('tickets', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tickets', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.execute("UPDATE tickets SET priority = COALESCE(priority_id, 'normal') WHERE priority IS NULL")
    op.alter_column('tickets', 'priority',
               existing_type=mysql.ENUM('low', 'normal', 'high', 'urgent'),
               nullable=False,
               server_default=None)
    op.create_index(op.f('ix_tickets_assigned_to'), 'tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tickets_client_id'), 'tickets', ['client_id'], unique=False)
    op.create_index(op.f('ix_tickets_updated_by'), 'tickets', ['updated_by'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.drop_column('tickets', 'priority_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('priority_id', mysql.ENUM('low', 'normal', 'high', 'urgent'), nullable=True))
    op.execute("UPDATE tickets SET priority_id = priority WHERE priority_id IS NULL")
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_updated_by'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_client_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to'), table_name='tickets')
    op.alter_column('tickets', 'updated_at',
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('tickets', 'created_at',
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tickets', 'status',
               existing_type=mysql.ENUM('pending', 'in_process', 'done', 'canceled'),
               nullable=True)
    op.alter_column('tickets', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('tickets', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('tickets', 'priority')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_author_id'), table_name='ticket_messages')
    op.alter_column('ticket_messages', 'updated_at',
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('ticket_messages', 'created_at',
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ticket_messages', 'is_internal',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('ticket_messages', 'message',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
