name: Deploy do Setor - Gabriele (Squad 4)

on:
  push:
    branches: [ "develop" ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixar o código do repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Login no Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_GABRIELE }}
          password: ${{ secrets.DOCKERHUB_TOKEN_GABRIELE }}

      # 3. Build da imagem e envio para o seu Docker Hub pessoal
      - name: Build e Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME_GABRIELE }}/projeto-setor:latest

      # 4. Deploy Remoto na VM via SSH
      - name: Deploy na VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Baixa a versão mais recente da SUA imagem
            docker pull ${{ secrets.DOCKERHUB_USERNAME_GABRIELE }}/projeto-setor:latest
            
            docker stop container-setor-gabriele || true
            docker rm container-setor-gabriele || true
            
            # Roda o container na porta 8084 (Squad 4)
            # Mapeando a porta 8084 da VM para a 80 do seu container
            docker run -d \
              --name container-setor-gabriele \
              -p 8084:80 \
              ${{ secrets.DOCKERHUB_USERNAME_GABRIELE }}/projeto-setor:latest
